- blocks/header/header.css
- blocks/header/header.js
Fix #19 
Test URLs:
- After: https://issue-19-nav-scrolling-bug--vonage--hlxsites.hlx.page/unified-communications/
Changes:
- Nav menu is now 'sticky' and will remain at the top of the page when scrolled
- Nav menu now collapses the upper tools section and swaps to a smaller logo on scroll down of a sufficient length (160 pixels) and reverts immediately on any scroll up event
- Also addresses a mistake I missed where the nav-drop decorations border property was nixed resulting in the little chevrons for the drop down nav menus no longer rendering.
This is currently lacking a transition / delay on the transform as the clients own site does (a quarter second), so might want to come back and implement that later but …
> Issue #19 - bug: nav menu doesn't persist on page when scrolling

- blocks/footer/footer.css
- blocks/header/header.css
- blocks/pricing-matrix/pricing-matrix.css
- fonts/VltIcons.ttx
- styles/styles.css
No tangible change, just a refactor to provide aliases for icons to make things a little easier to read and author.
Fix #44
Test URLs:
- After: https://issue-44-svg-font-icons--vonage--hlxsites.hlx.page/unified-communications/
> Adding icon aliases and updating references

- blocks/cards/cards.css
@jimaldous here's a fix that I think should address the issue with the arrow positioning (as well as a problem with the font size I found while comparing to the clients site). 
Fix #N/A
Test URLs:
- Before: https://issue-64-info-card-vertical--vonage--hlxsites.hlx.page/unified-communications/features/admin-portal
- After: https://issue-64-info-cards-fixing-arrows--vonage--hlxsites.hlx.page/unified-communications/features/admin-portal
> Style tweaks

- blocks/cards/cards.css
Changed flex direction for info-cards to make both elements in the row stretch to the same height.
Fix #64
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/features/admin-portal
- After: https://issue-64-info-card-vertical--vonage--hlxsites.hlx.page/unified-communications/features/admin-portal
> issue-64 Change info-card flex direction to fix vertical alignment.

- blocks/cards/cards.css
- blocks/header/header.css
- blocks/header/header.js
- scripts/scripts.js
- styles/styles.css
Fix #5
Test URLs:
1st tier page:
- After: https://issue-5-subnav--vonage--hlxsites.hlx.page/unified-communications/
- Client: https://www.vonage.com/unified-communications/
2nd tier page:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/features
- After: https://issue-5-subnav--vonage--hlxsites.hlx.page/unified-communications/features
- Client: https://www.vonage.com/unified-communications/features/
3rd tier page:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/features/desktop
- After: https://issue-5-subnav--vonage--hlxsites.hlx.page/unified-communications/features/desktop
- Client: https://www.vonage.com/unified-communications/features/desktop/
Known issues:
Notes: …
> Issue 5 subnav

- styles/styles.css
Don't need it on the top and bottom of each section element
Fix #65
Test URLs:
- After: https://issue-65-address-padding-between-sections--vonage--hlxsites.hlx.page/unified-communications/
> Addressing over padding in section layout

- blocks/columns/columns.css
There were a couple of selectors in columns.css which were not scoped to just the columns block and as such were impacting the elements of other blocks (such as the nav bread crumb)
Fix #93
Test URLs:
- After: https://issues-93-fix-nav-width--vonage--hlxsites.hlx.page/unified-communications/
> Addressing overly global columns selector

- blocks/pricing-matrix/pricing-matrix.css
Fix #107 - Bit of a hack, but don't think it's worth spending the time time digging into the underlying why of this behavior if this style adjustment fixes the issue.
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/pricing
- After: https://issues-107-pricing-matrix-hf--vonage--hlxsites.hlx.page/unified-communications/pricing
> Fixing background color not extending to full block height

- blocks/columns/columns.css
Test URLs:
- After: https://slim-promo-padding--vonage--hlxsites.hlx.live/unified-communications/
> remove padding from slim-promo

- blocks/fragment/fragment.css
Bullet should be purple from what I see in the clients page. 
Fix #N/A
Test URLs:
- After: https://hf-fragment-bullet-color--vonage--hlxsites.hlx.page/unified-communications/pricing/
> Setting bullet color to purple

- styles/styles.css
For the little disclaimer text that comes in below this 2-col fragment.  Note that I think there needs to be some adjustment to the padding in the 2-col fragment block (think we are double dipping on padding and not filing the available page space, will tackle that as a fix next. 
Fix #N/A
Test URLs:
- After: https://hf-fragment-disclaimer-text--vonage--hlxsites.hlx.page/unified-communications/pricing/
> Fixing default text style after phone service content fragment

- styles/styles.css
Hotfix for the default content wrapper styling on the pricing page that was mentioned in the sync call.
Turns out the styling was section dependent and the pricing page had a different section named.
Fix #N/A
Test URLs:
- After: https://hf-default-content-styling--vonage--hlxsites.hlx.page/unified-communications/pricing/
> Default-content-wrapper font styling incorrect in pricing page

- blocks/fragment/fragment.css
Fixing up the margins / padding for the 2-column fragment, and introducing wrap behavior at smaller resolutions. 
Fix N/A
Test URLs:
- After: https://hf-addressing-column-fragment-padding--vonage--hlxsites.hlx.page/unified-communications/pricing/
> Hf addressing column fragment padding and wrap

- blocks/faceted-search/faceted-search.css
Adding the matching text in the markdown, and styling it in the phone search block via default-content-wrapper
Fix #N/A
Test URLs:
- After: https://hf-styling-text-above-phone-search-container--vonage--hlxsites.hlx.page/unified-communications/pricing/
> Styling pre phone search text

- blocks/columns/columns.css
Color shouldn't have been defined in the block, instead handled in the section. 
Fix #N/A
Test URLs:
- After: https://hf-case-study-bg-color--vonage--hlxsites.hlx.page/unified-communications/
> Removing background-color on case study column

- blocks/header/header.css
Fix #82
Test URLs:
- After: https://issue-82-nav-underline--vonage--hlxsites.hlx.page/unified-communications/
Before:
After:
> Nav underline does not extend to full width of the span

- blocks/header/header.js
Fix #77 - Adding a document level click handler that will close a navSection menu if open, as well as a similar handler for the breadcrumb
Test URLs:
- After: https://issue-77-outside-nav-click-closer--vonage--hlxsites.hlx.page/unified-communications/
> Adding outside menu click handlers to close menus

- blocks/columns/columns.css
- blocks/columns/columns.js
- blocks/fragment/fragment.css
Fix #123 
Added support for columns block to wrap the image column in an <a> by including a link after the image in the markdown. 
Fixed styling for inline links in the detail text of the column block (both those loaded via fragments and not)
Confirmed that the detail-columns block variant introduced by @jimaldous was not affected via these changes through his own drafts page:
https://main--vonage--hlxsites.hlx.page/drafts/columns-details-columns
https://issue-123-2-col-fragment--vonage--hlxsites.hlx.page/drafts/columns-details-columns
Other than the correction on link text color and decoration.
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/platform
- After: https://issue-123-2-col-fragment--vonage--hlxsites.hlx.page/unified-communications/
> Virtualization column does not render correctly

- blocks/cards/cards.css
Fix #138 
Added a new variant to the cards block to allow specifying for large icons via Cards(large-icon)
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/insurance
- After: https://issue-138-small-card-images--vonage--hlxsites.hlx.page/unified-communications/insurance
> Card images are too small 

- blocks/fragment/fragment.css
Fix #132 
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/global
- After: https://issue-132-default-text-after-column--vonage--hlxsites.hlx.page/unified-communications/global
> Styling for end note after column fragments

- blocks/fragment/fragment.css
- blocks/jump-links/jump-links.css
- blocks/jump-links/jump-links.js
New block jumpLinks, only seen used in the global-calling-plans page but necessary IMHO. 
Fix #136
Test URLs:
Before: https://main--vonage--hlxsites.hlx.page/unified-communications/global/global-calling-plans
After: https://issue-136-jumpLinks--vonage--hlxsites.hlx.page/unified-communications/global/global-calling-plans
> Jump link block

- blocks/columns/columns.css
- blocks/columns/columns.js
Handling the world office location (which could justifiably have been it's own block) but running it through the column block with some section based styling.
Fix #135
Draft available here: https://issue-135-world-office-locations--vonage--hlxsites.hlx.page/drafts/dgranber/columns-headerlist
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/global/world-office-locations
- After: https://issue-135-world-office-locations--vonage--hlxsites.hlx.page/unified-communications/global/world-office-locations
> Styling for the world office location column variant

- blocks/columns/columns.css
- blocks/jump-links/jump-links.css
- blocks/jump-links/jump-links.js
- blocks/pricing-grid/pricing-grid.css
- blocks/pricing-grid/pricing-grid.js
- tools/importer/import.js
Pricing grid block necessary for the global-calling-plans page.
Fix #137
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/global/global-calling-plans
- After: https://issue-137-pricinggrid--vonage--hlxsites.hlx.page/unified-communications/global/global-calling-plans
Draft available here:
https://issue-137-pricinggrid--vonage--hlxsites.hlx.page/drafts/dgranber/pricing-grid
Notes: 
Pulls pricing data relative to the page housing the component, executes a call for `${window.location.pathname}/pricing/data.json`
The data in the file should have a suitable number of sheets (pricing tier data which for now is just two tiers) and each sheet should have pricing information for 1 or more currencies associated to minute plan values as well as the desired label to …
> Issue 137 pricing grid
