hlxsites/Vonage

blocks/header/header.css, blocks/header/header.js, styles/styles.css
Fix #18 
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.live/unified-communications/ (preview is wonky as this PR required a refactor of the nav content in drive to have the search icon in a separate section)
- After:  https://issue-18-nav-mobile--vonage--hlxsites.hlx.page/unified-communications/
Notes: 
- Content will need to be published once this PR is merged (nav)
- I added a margin-top style rule for the body in order to prevent the body content from slipping under the fixed nav menu
- Had to switch from using an externally loaded SVG to an inline declared one in order to be able to apply styling to it dynamically (to change color …
=> Issue 18 nav mobile

blocks/footer/footer.css, blocks/footer/footer.js, styles/styles.css
Provided implementation for footer block.
Fix #2
Test URLs:
- After: https://issue-2-footer--vonage--hlxsites.hlx.page/unified-communications/
=> issue-2: Add updates to js and css for footer block

blocks/fragment/fragment.css, blocks/fragment/fragment.js
Fix #N/A Content Fragment for two columns
Test URLs:
- After: https://fragment-2-col--vonage--hlxsites.hlx.page/unified-communications/
=> Fragment 2 col

blocks/footer/footer.css, blocks/footer/footer.js
New JS and CSS to simplify footer implementation.
Fix #37
Test URLs:
- After: https://issue-37-simplify-footer--vonage--hlxsites.hlx.page/unified-communications/
=> issue-37 Simplify footer

blocks/header/header.css, styles/styles.css
Fixes CLS by header loading.
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.live/unified-communications/
- After: https://fix-cls--vonage--hlxsites.hlx.live/unified-communications/
=> fix header cls

blocks/cards/cards.css
Just updated the gradient-shadow.
Fix #6 
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.live/unified-communications/
- After: https://cards-6--vonage--hlxsites.hlx.live/unified-communications/
=> Cards gradient-shadow variant

blocks/qanda/qanda.css, blocks/qanda/qanda.js
Fix #29 
Test URLs:
- After: https://issue-29-q-and-a--vonage--hlxsites.hlx.page/drafts/qanda
=> Issue 29 q and a

blocks/cards/cards.css, blocks/cards/cards.js, blocks/columns/columns.css, styles/styles.css
Implemented card behavior where the whole card is the link anchor.
Fix #54
Test URLs:
- After: https://issue-54-card-link--vonage--hlxsites.hlx.page/unified-communications/
=> issue-54 card-link implementation

blocks/cards/cards.css, blocks/columns/columns.css
Fixed styling for columns found on `features/admin-portal` page, and for the "info-card" cards found on that page and the main `unified-communications` page.
Fix #62
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/features/admin-portal
- After: https://issue-62-admin-portal--vonage--hlxsites.hlx.page/unified-communications/
- After: https://issue-62-admin-portal--vonage--hlxsites.hlx.page/unified-communications/features/admin-portal
=> issue-62 Fixes to columns and info-card styling for admin-portal page

blocks/columns/columns.css
Fix #70 
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/drafts/columns-category-grid
- After: https://70-columns-category-grid--vonage--hlxsites.hlx.page/drafts/columns-category-grid
=> add category-grid support

blocks/speed-bump/speed-bump.css, blocks/speed-bump/speed-bump.js, styles/styles.css
Fix #73
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/platform
- After: https://73-block-speed-bump--vonage--hlxsites.hlx.page/unified-communications/platform
- After: https://73-block-speed-bump--vonage--hlxsites.hlx.page/drafts/speed-bump
=> *new* speed bump block

blocks/cards/cards.css
Fix #74 
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/platform
- After: https://74-cards-logo-strip--vonage--hlxsites.hlx.page/unified-communications/platform
- After: https://74-cards-logo-strip--vonage--hlxsites.hlx.page/drafts/cards-logo-strip
=> *new* variation: logo-strip

blocks/columns/columns.css
Test URLs:
- After: https://misc-col-fixes--vonage--hlxsites.hlx.page/unified-communications/
=> misc columns fixes

blocks/fragment/fragment.js, blocks/qanda/qanda.js, scripts/scripts.js, styles/lazy-styles.css
Fix #98
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/integrations
- After: https://98-modal-dialog--vonage--hlxsites.hlx.page/unified-communications/integrations
=> feat #98: Modal Dialog on button click

blocks/columns/columns.css, blocks/header/header.js, blocks/landing-page-hero/landing-page-hero.css, blocks/qanda/qanda.js, styles/styles.css
Test URLs:
- After: https://clean1--vonage--hlxsites.hlx.page/unified-communications/
=> various CSS cleanup of main page

blocks/header/header.css
Fix #78
Test URLs:
- After: https://issue-78-breadcrumb-fade-in--vonage--hlxsites.hlx.page/unified-communications/
=> Breadcrumb fadein animation is not triggering

blocks/header/header.css, blocks/header/header.js
Fix #81
Test URLs:
- After: https://issue-81-highlight-active-nav-sub-section--vonage--hlxsites.hlx.page/unified-communications/
=> Correcting sub menu index highlighting behavior

blocks/cards/cards.css, blocks/columns/columns.css, blocks/columns/columns.js
Adds support for "columns (details-columns)", slightly structured content on one side and an image (with optional link) on the other.
Also added "either-side" capability to "case-study" style of columns.
Other minor fix to "info-card" to fix vertical alignment.
Fix #106
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/use-cases
- Before: https://main--vonage--hlxsites.hlx.page/drafts/columns-details-columns
- After: https://issue-106-details-columnns--vonage--hlxsites.hlx.page/unified-communications/use-cases
- After: https://issue-106-details-columnns--vonage--hlxsites.hlx.page/drafts/columns-details-columns
=> Issue 106 details-columns

404.html
Fix #104
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.live/unified-communications/test
- After: https://104-not-found--vonage--hlxsites.hlx.live/404.html
=> update 404 page

blocks/columns/columns.css, blocks/columns/columns.js
Fix #120 
* Added the View Offer button as seen in the clients page at < 768px display width as well as a close button.
* Setup the View Offer button as well as a click on the h2 in mobile mode to trigger expansion of the block and rendering of the detail <p>
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/features/desktop
- After: https://issue-120-mobile-slim-promo--vonage--hlxsites.hlx.page/unified-communications/features/desktop
=> [Mobile] Slim Promo button not visible and not clickable 

blocks/columns/columns.css
For supported countries list page.
Fix #133 
Test URLs:
- Before: https://main--vonage--hlxsites.hlx.page/unified-communications/global/supported-countries
- After: https://issue-133-country-list--vonage--hlxsites.hlx.page/unified-communications/global/supported-countries
=> Adding a 4 column text block variant
